name: start_journey
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  curved_navigation_bar: ^1.0.3
  intl_phone_field: ^3.2.0
  dartz: ^0.10.1
  http: ^1.2.1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  yandex_mapkit: ^4.0.2
  geolocator: ^13.0.4
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  permission_handler: ^12.0.0+1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  #firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  uuid: ^4.5.1
  internet_connection_checker_plus: ^2.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: any
  build_runner: any
  json_serializable: any
  built_value_generator: any
  hive_generator: any

flutter_gen:
  output: lib/shared/constants/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
      - images/
      - images/regions/
      - images/myIcons/
      - images/amenitiesIcon/
      - images/hotels/sheraton_bishkek/
      - images/hotels/jannat_resort/
      - images/sights/ruh_ordo/
      - images/sights/canyon_fairy_tale/
      - images/delete/
      - images/journal/dog.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
